spring:
  application:
    name: java-openlineage-app
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/java_openlineage_poc_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
openlineage:
  config:
    location: classpath:openlineage.yml
server:
  port: 8087
kafka:
  topics:
    sales-transaction: "sales-transaction"
    enriched-sales-transaction: "enriched-sales-transaction"
